### ISSUE TITLE
EnvironmentVariablesUtils: NullPointerException si le fichier ENVIRONMENT.properties n'existe pas

### ISSUE THREAD

**Issue by zacharyarnaise** [B4va/alternbot-app#35]
https://github.com/B4va/alternbot-app/blob/367ed05015692b7ce6e2c7e5546bd65c6acf9b75/src/main/java/utils/EnvironmentVariablesUtils.java#L124-L128

Si une variable demandée n'est pas trouvée dans les variables d'environnement du système, la fonction `getFromFile` est appelée mais celle-ci génère une exception `NullPointerException` lors de l'appel `prop.load(inputStream)` si le fichier défini par `ENVIRONMENT_VARIABLES_FILE` n'existe pas.

C'est un bug qui ne nous dérangera pas dans l'immédiat puisque tout le monde a son environnement de travail configuré comme il faut mais je le report quand même parce que ça m'a fait perdre un peu de temps quand je suis tombé dessus en testant la CI sur mon fork (donc sans fichier `ENVIRONMENT.properties`) suite à #30.

Je m'étais contenté de faire ça pour résoudre le soucis mais il y a peut être plus clean:
```java
private static String getFromFile(String variable) { 
   try { 
     try (InputStream inputStream = EnvironmentVariablesUtils.class.getResourceAsStream(ENVIRONMENT_VARIABLES_FILE)) { 
       if (Objects.isNull(inputStream))
         return null;
       . . .
```

**Comment by B4va** [comment]
L'erreur est corrigée par cette PR : #39 ; voir si l'implémentation doit quand même être améliorée.

**Comment by zacharyarnaise** [comment]
J'ai vu la modif passer et je pense que ça sera suffisant. Le principal problème c'était que quand ça arrivait c'était pas évident à diagnostiquer alors que là c'est mieux.
