### ISSUE TITLE
Le fichier .ics généré lors de l'export de l'emploi du temps génère tous les cours avec un décalage d'une heure dans le futur

### ISSUE THREAD

**Issue by novachrono67** [B4va/alternbot-app#97]
![image](https://user-images.githubusercontent.com/71826596/114267370-6d07c980-99fb-11eb-8a64-c6d4859d522f.png)

Comme indiqué dans l'image, tous les cours sont générés avec un décalage d'une heure vers le future. 
A noter que l'import des cours fonctionne correctement dans google calendar par exemple, et qu'il a fonctionné correctement dans Outlook jusque fin Mars.
Je suspecte fortement que le changement d'heure (heure d'été -> dimanche 28 mars 2021 à 2h de matin) pose un soucis ici, mais je n'ai pas encore trouvé le soucis dans le fichier.

**Comment by novachrono67** [comment]
Les dates, horaires et timezones dans le fichier .ics sont d'ailleurs exact, mais les cours sont tout de même généré avec une heure de décallage.

**Comment by zacharyarnaise** [comment]
@novachrono67 Je pense avoir trouvé la cause de ce soucis. Est-ce que tu peux faire un test avec ce fichier et voir si le problème est résolu ?
[edt_10-04-2021_fix.zip](https://github.com/B4va/alternbot-app/files/6289951/edt_10-04-2021_fix.zip)

**Comment by novachrono67** [comment]
@zacharyarnaise oui, problème résolu ? C'était dû à quoi?

**Comment by zacharyarnaise** [comment]
Il manquait un bloc en début de fichier pour "décrire" la timezone utilisée. Les autres softs arrivent à gérer sans ça mais pas Outlook à priori.
Si c'est bon du coup je peux ouvrir une PR avec les modifications 👍

**Comment by B4va** [comment]
> Il manquait un bloc en début de fichier pour "décrire" la timezone utilisée. Les autres softs arrivent à gérer sans ça mais pas Outlook à priori.
> Si c'est bon du coup je peux ouvrir une PR avec les modifications 👍  

Si tu as la correction en tête autant faire la PR tout de suite du coup oui :)
